stages:
  data_ingestion:
    cmd: python main.py --stage data_ingestion
    deps:
      - src/AutoClaimML/components/data_ingestion.py
      - src/AutoClaimML/pipeline/training_pipeline.py
    outs:
      - artifacts/data_ingestion/

  data_validation:
    cmd: python main.py --stage data_validation
    deps:
      - src/AutoClaimML/components/data_validation.py
      - artifacts/data_ingestion/
    outs:
      - artifacts/data_validation/
 

