stages:
   data_ingestion:
      cmd: python main.py 
      deps:
        - src/pipeline/training_pipeline.py
        - src/components/data_ingestion.py
        - src/configuration/configuration.py
        - src/entity/config_entity.py
        - src/entity/artifact_entity.py
        - src/data_access/vehicle_db.py
        - src/configuration/mongo_db_connection.py
      outs:
        - artifacts/05_26_2025_14_52_20/data_ingestion/ingested/train.csv
        - artifacts/05_26_2025_14_52_20/data_ingestion/ingested/test.csv